version: "3.7"

services:
  web:
    build:
      context: ./
    image: web-image
    container_name: web-image
    expose:
      - "80"
  proxy:
    image: nginx:alpine
    container_name: web-proxy
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - web
